language: php
sudo: false

# Use the distro precise to avoid random issues with composer.
# See: https://github.com/AOEpeople/MageTestStand/issues/22
dist: precise

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2
env:
  - MAGENTO_VERSION="magento-mirror-1.9.3.8"

script:
- curl -sSL https://raw.githubusercontent.com/gpaddis/MageTestStand/master/setup.sh | bash